spring:
  main:
    banner-mode: "console"
    output:
      ansi:
        enabled: always
  application:
    name: ai-service
  profiles:
    active: dev
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      audio:
        speech:
          model: gpt-4o-mini-tts
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # Spring Cloud Configuration
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
server:
  port: 8087

# Eureka Configuration
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${random.uuid}

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Cấu hình Feign Client
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

# Cấu hình Resilience4j (Circuit Breaker)
resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 500ms

# AI Service Configuration
ai-service:
  tts:
    storage-path: ${TTS_STORAGE_PATH:./storage/tts}
  speech-analysis:
    python-service-url: ${PYTHON_SERVICE_URL:http://localhost:8000}
  openai:
    default-model: gpt-4o
    economy-model: gpt-3.5-turbo 