spring:
  main:
    banner-mode: "console"
    output:
      ansi:
        enabled: always
  application:
    name: nihongo-it-backend
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/NihongoIT
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: never
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      audio:
        speech:
          model: gpt-4o-mini-tts
server:
  port: 8080

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 2592000000  # 30 days for language learning apps


# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html